apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-c905"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-c905"
  template:
    metadata:
      labels:
        app: "tdedahaks-c905"
    spec:
      containers:
        - name: "tdedahaks-c905"
          image: "deepak2121.azurecr.io/tdedahaksc905"
          ports:
          - containerPort: 4000