apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-b6f3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-b6f3"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-b6f3"
    spec:
      containers:
        - name: "aaaatiwarishubaks-b6f3"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaksb6f3"
          ports:
          - containerPort: 4000