apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-c866"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-c866"
  template:
    metadata:
      labels:
        app: "tdedahaks-c866"
    spec:
      containers:
        - name: "tdedahaks-c866"
          image: "deepak2121.azurecr.io/tdedahaksc866"
          ports:
          - containerPort: 4000