apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-71b5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-71b5"
  template:
    metadata:
      labels:
        app: "tdedahaks-71b5"
    spec:
      containers:
        - name: "tdedahaks-71b5"
          image: "deepak2121.azurecr.io/tdedahaks71b5"
          ports:
          - containerPort: 4000