apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-2579"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-2579"
  template:
    metadata:
      labels:
        app: "tdedahaks-2579"
    spec:
      containers:
        - name: "tdedahaks-2579"
          image: "deepak2121.azurecr.io/tdedahaks2579"
          ports:
          - containerPort: 4000