apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-e3cb"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-e3cb"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-e3cb"
    spec:
      containers:
        - name: "aaaatiwarishubaks-e3cb"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubakse3cb"
          ports:
          - containerPort: 4000