apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-1602"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-1602"
  template:
    metadata:
      labels:
        app: "tdedahaks-1602"
    spec:
      containers:
        - name: "tdedahaks-1602"
          image: "deepak2121.azurecr.io/tdedahaks1602"
          ports:
          - containerPort: 4000