apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-3983"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-3983"
  template:
    metadata:
      labels:
        app: "tdedahaks-3983"
    spec:
      containers:
        - name: "tdedahaks-3983"
          image: "deepak2121.azurecr.io/tdedahaks3983"
          ports:
          - containerPort: 4000