apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-0c6a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-0c6a"
  template:
    metadata:
      labels:
        app: "tdedahaks-0c6a"
    spec:
      containers:
        - name: "tdedahaks-0c6a"
          image: "deepak2121.azurecr.io/tdedahaks0c6a"
          ports:
          - containerPort: 4000