apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-e3b6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-e3b6"
  template:
    metadata:
      labels:
        app: "tdedahaks-e3b6"
    spec:
      containers:
        - name: "tdedahaks-e3b6"
          image: "deepak2121.azurecr.io/tdedahakse3b6"
          ports:
          - containerPort: 4000