apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-4066"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-4066"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-4066"
    spec:
      containers:
        - name: "aaaatiwarishubaks-4066"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaks4066"
          ports:
          - containerPort: 4000