apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-3a16"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-3a16"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-3a16"
    spec:
      containers:
        - name: "aaaatiwarishubaks-3a16"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaks3a16"
          ports:
          - containerPort: 80