apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-af1a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-af1a"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-af1a"
    spec:
      containers:
        - name: "aaaatiwarishubaks-af1a"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaksaf1a"
          ports:
          - containerPort: 4000