apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tdedahaks-e543"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tdedahaks-e543"
  template:
    metadata:
      labels:
        app: "tdedahaks-e543"
    spec:
      containers:
        - name: "tdedahaks-e543"
          image: "deepak2121.azurecr.io/tdedahakse543"
          ports:
          - containerPort: 4000