apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-8b45"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-8b45"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-8b45"
    spec:
      containers:
        - name: "aaaatiwarishubaks-8b45"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaks8b45"
          ports:
          - containerPort: 4000