apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "diaggarw-9566"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "diaggarw-9566"
    spec:
      containers:
        - name: "diaggarw-9566"
          image: ".azurecr.io/diaggarw9a62"
          ports:
          - containerPort: 80
