apiVersion: v1
kind: Service
metadata:
    name: "aaaaabugbashprovsvcrouting-a01c"
    labels:
        app: "aaaaabugbashprovsvcrouting-a01c"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aaaaabugbashprovsvcrouting-a01c"