apiVersion: v1
kind: Service
metadata:
    name: "tdedahaks-ae5f"
    labels:
        app: "tdedahaks-ae5f"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "tdedahaks-ae5f"