apiVersion: v1
kind: Service
metadata:
    name: "aaaatiwarishubaks-b6f3"
    labels:
        app: "aaaatiwarishubaks-b6f3"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aaaatiwarishubaks-b6f3"