apiVersion: v1
kind: Service
metadata:
    name: "aaaaabugbashprovsvc-bd4b"
    labels:
        app: "aaaaabugbashprovsvc-bd4b"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aaaaabugbashprovsvc-bd4b"
